load("@bazel_skylib//lib:partial.bzl", "partial")
load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//diff:defs.bzl", "diff", "sdiff")

sdiff(
    name = "case_sdiff",
    srcs = [
        partial.make(
            write_file,
            content = [
                "hello",
                "moo",
                "cow",
                "",
            ],
        ),
        partial.make(
            write_file,
            content = [
                "hello",
                "foo",
                "bar",
                "",
            ],
        ),
    ],
)

diff(
    name = "case_sdiff_assert_output",
    srcs = [
        ":case_sdiff",
        partial.make(
            write_file,
            content = [
                "hello								hello",
                "moo							      |	foo",
                "cow							      |	bar",
                "",
            ],
        ),
    ],
    validate = 1,
)

genrule(
    name = "case_genrule",
    srcs = [],
    outs = ["sdiff_help.txt"],
    cmd = "$(SDIFF_BIN) --help > $@",
    toolchains = ["@diff.bzl//diff/toolchain:execution_type"],
)

build_test(
    name = "build_test",
    targets = [
        ":case_sdiff",
        ":case_sdiff_assert_output",
        ":case_genrule",
    ],
)
