load("@bazel_lib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "cmp",
    srcs = [
        "cmp.bzl",
        "options.bzl",
    ],
    visibility = ["//diff:__subpackages__"],
)

bzl_library(
    name = "diff",
    srcs = [
        "diff.bzl",
        "options.bzl",
    ],
    visibility = ["//diff:__subpackages__"],
)
