load("@bazel_lib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "diff",
    srcs = ["diff.bzl"],
    visibility = ["//diff:__subpackages__"],
)

bzl_library(
    name = "toolchains_repo",
    srcs = ["toolchains_repo.bzl"],
    visibility = ["//diff:__subpackages__"],
)

bzl_library(
    name = "versions",
    srcs = ["versions.bzl"],
    visibility = ["//diff:__subpackages__"],
)

bzl_library(
    name = "resolved_toolchain",
    srcs = ["resolved_toolchain.bzl"],
    visibility = ["//diff:__subpackages__"],
)
