"""Create a repository to hold the diffutils toolchains

This follows guidance here:
https://docs.bazel.build/versions/main/skylark/deploying.html#registering-toolchains
"""

# Platforms for binaries published in https://github.com/kormide/diffutils-prebuilt.
PLATFORMS = {
    "linux_amd64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux_arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "darwin_amd64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "darwin_arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "windows_amd64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
}

def _toolchains_repo_impl(rctx):
    build_content = """# Generated by @diff.bzl//diff/private/toolchains_repo.bzl
#
# These can be registered in MODULE.bazel or passed to --extra_toolchains flag.
# By default all these toolchains are registered by the diffutils_register_toolchains macro
# so you don't normally need to interact with these targets.

"""

    for [platform, meta] in PLATFORMS.items():
        build_content += """
toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:diffutils_toolchain",
    toolchain_type = "@diff.bzl//diff/toolchain:execution_type",
)

toolchain(
    name = "{platform}_target_toolchain",
    target_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:diffutils_toolchain",
    toolchain_type = "@diff.bzl//diff/toolchain:target_type",
)

""".format(
            platform = platform,
            user_repository_name = rctx.attr.user_repository_name,
            compatible_with = meta.compatible_with,
        )

    rctx.file("BUILD.bazel", build_content)

toolchains_repo = repository_rule(
    _toolchains_repo_impl,
    doc = """Creates a repository with toolchain definitions for all known platforms
     which can be registered or selected.""",
    attrs = {
        "user_repository_name": attr.string(doc = "what the user chose for the base name"),
    },
)
