"""Declare toolchain setup
"""

load("//diff/private:toolchains_repo.bzl", "PLATFORMS", "toolchains_repo")
load("//diff/private:versions.bzl", "TOOL_VERSIONS")

_DOC = "Fetch external tools needed for diff toolchain"
_ATTRS = {
    "version": attr.string(values = TOOL_VERSIONS.keys()),
    "platform": attr.string(values = PLATFORMS.keys()),
    "use_system_diff": attr.bool(default = False),
}

def _diff_repo_impl(repository_ctx):
    use_system_diff = repository_ctx.attr.use_system_diff
    if not use_system_diff:
        fail("Hermetic diff tools are not yet supported")
    build_content = """# Generated by diff/repositories.bzl
load("@diff.bzl//diff:toolchain.bzl", "diffutils_toolchain")

diffutils_toolchain(
    name = "diffutils_toolchain",
    use_system_diff = repository_ctx.attr.use_system_diff,
)
"""

    # Base BUILD file for this repository
    repository_ctx.file("BUILD.bazel", build_content)

diff_repositories = repository_rule(
    _diff_repo_impl,
    doc = _DOC,
    attrs = _ATTRS,
)

# Wrapper macro around everything above, this is the primary API
def diff_register_toolchains(name, register = True, **kwargs):
    """Convenience macro for users which does typical setup.

    - create a repository for each built-in platform like "diff_linux_amd64"
    - TODO: create a convenience repository for the host platform like "diff_host"
    - create a repository exposing toolchains for each platform like "diff_platforms"
    - register a toolchain pointing at each platform
    Users can avoid this macro and do these steps themselves, if they want more control.

    Args:
        name: base name for all created repos, like "diff1_14"
        register: whether to call through to native.register_toolchains.
            Should be True for WORKSPACE users, but false when used under bzlmod extension
        **kwargs: passed to each diff_repositories call
    """
    for platform in PLATFORMS.keys():
        diff_repositories(
            name = name + "_" + platform,
            platform = platform,
            **kwargs
        )
        if register:
            native.register_toolchains("@%s_toolchains//:%s_toolchain" % (name, platform))

    toolchains_repo(
        name = name + "_toolchains",
        user_repository_name = name,
    )
