load("@bazel_skylib//lib:partial.bzl", "partial")
load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//diff:defs.bzl", "cmp", "diff")

cmp(
    name = "case_cmp_same_binary",
    srcs = [
        "case_cmp_same_binary.a",
        "case_cmp_same_binary.b",
    ],
    validate = 1,
)

cmp(
    name = "case_cmp_different_binary",
    srcs = [
        "case_cmp_different_binary.a",
        "case_cmp_different_binary.b",
    ],
)

diff(
    name = "case_cmp_different_binary_assert_output",
    srcs = [
        ":case_cmp_different_binary",
        partial.make(
            write_file,
            content = [
                "diff/tests/cmp/case_cmp_different_binary.a diff/tests/cmp/case_cmp_different_binary.b differ: char 1, line 1",
                "",
            ],
        ),
    ],
    validate = 1,
)

cmp(
    name = "case_cmp_verbose",
    srcs = [
        "case_cmp_verbose.a",
        "case_cmp_verbose.b",
    ],
    args = ["--verbose"],
)

diff(
    name = "case_cmp_verbose_assert_output",
    srcs = [
        ":case_cmp_verbose",
        partial.make(
            write_file,
            content = [
                "1 125  10",
                "2 142  77",
                "3  46 171",
                "4  41 312",
                "5  62 134",
                "6 315 353",
                "7 231 360",
                "8 231 167",
                "",
            ],
        ),
    ],
    validate = 1,
)

genrule(
    name = "case_genrule",
    srcs = [],
    outs = ["cmp_help.txt"],
    cmd = "$(CMP_BIN) --help > $@",
    toolchains = ["@diff.bzl//diff/toolchain:execution_type"],
)

build_test(
    name = "build_test",
    targets = [
        ":case_cmp_same_binary",
        ":case_cmp_different_binary",
        ":case_cmp_different_binary_assert_output",
        ":case_cmp_verbose",
        ":case_cmp_verbose_assert_output",
        ":case_genrule",
    ],
)
