"See https://docs.bazel.build/versions/main/toolchains.html"

package(default_visibility = ["//visibility:public"])

# Resolve a 'diffutils' toolchain for the execution platform.
toolchain_type(name = "toolchain_type")
